spring:
logging:
  level:
    org.springframework: INFO
    com.sb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread, %X{mdc_Key_1}] %-5level %logger{36}:  %X{mdc_Key_1} - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread, %X{mdc_Key_1}] %-5level %logger{36}:  %X{mdc_Key_1} - %m%n"
server:
  port: 4085

    
one:
  two:
    three:
      key1: mapValue1
      key2: mapValue2
    four:
      key1: mapValue1
      key2: mapValue2