FROM openjdk:8
ADD target/sample-car-booking-app-dmp-1.0.0-SNAPSHOT.jar sample-car-booking-app-dmp-1.0.0-SNAPSHOT.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "sample-car-booking-app-dmp-1.0.0-SNAPSHOT.jar"]